# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

parameters:
  - name: sourceDB
    type: string
    default: 'sourceDB'
  - name: targetDB
    type: string
    default: 'targetDB'

jobs:
- job: CopyDatabase
  displayName: 'Copy Database from Source to Target'
  pool: azrelease
  steps:
  - task: AzureCLI@2
    displayName: 'Azure Login'
    inputs:
      azureSubscription: '/subscriptions/664b6097-19f2-42a3-be95-a4a6b4069f6b/resourceGroups/sa1_test_eic_BhavikChhabria'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az login

  - task: AzureCLI@2
    inputs:
      azureSubscription: '/subscriptions/664b6097-19f2-42a3-be95-a4a6b4069f6b/resourceGroups/sa1_test_eic_BhavikChhabria'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az postgres server copy --source-db $(sourceDB) --target-db $(targetDB)
