# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
- name: sourceDB
  type: string
  default: 'sourcedb'
- name: targetDB
  type: string
  default: 'targetdb'

jobs:
- job: CopyDatabase
  displayName: 'Copy Database from Source to Target'
  pool: azrelease
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        az login
        az postgres flexible-server connect --name dbsource --admin-user source2 --admin-password 12_BHavik
        pg_dump -h dbsource.postgres.database.azure.com -U source2 postgres > new_backup2.dump
        psql -h targets1.postgres.database.azure.com -U source3 -d postgres
        psql -h targets1.postgres.database.azure.com -U source3 -d postgres -f new_backup.dump
      workingDirectory: '.'
